const data = [
  { symbol: "아", sound: "a (aa)" },
  { symbol: "어", sound: "eo (aww)" },
  { symbol: "오", sound: "o (oh)" },
  { symbol: "우", sound: "u (oo)" },
  { symbol: "으", sound: "eu (uh)" },
  { symbol: "이", sound: "i (ee)" },
  { symbol: "애", sound: "ae (eh)" },
  { symbol: "에", sound: "e (eh)" },
  { symbol: "외", sound: "oe (weh)" },
  { symbol: "위", sound: "wi (wee)" },
  { symbol: "ᄀ", sound: "g,k" },
  { symbol: "ᄂ", sound: "n" },
  { symbol: "ᄃ", sound: "d/t" },
  { symbol: "ᄅ", sound: "r,l" },
  { symbol: "ᄆ", sound: "m" },
  { symbol: "ᄇ", sound: "b/p" },
  { symbol: "ᄉ", sound: "s,sh" },
  { symbol: "ᄌ", sound: "j,ch" },
  { symbol: "ᄎ", sound: "ch" },
  { symbol: "ᄏ", sound: "k" },
  { symbol: "ᄐ", sound: "t" },
  { symbol: "ᄑ", sound: "p" },
  { symbol: "ᄒ", sound: "h" },
  { symbol: "ᄁ", sound: "kk" },
  { symbol: "ᄄ", sound: "tt" },
  { symbol: "ᄈ", sound: "pp" },
  { symbol: "ᄊ", sound: "ss" },
  { symbol: "ᄍ", sound: "jj" },
  { symbol: "야", sound: "ya" },
  { symbol: "여", sound: "yeo" },
  { symbol: "요", sound: "yo" },
  { symbol: "유", sound: "yu" },
  { symbol: "얘", sound: "yae" },
  { symbol: "예", sound: "ye" },
  { symbol: "와", sound: "wa" },
  { symbol: "왜", sound: "wae (wey)" },
  { symbol: "워", sound: "weo" },
  { symbol: "웨", sound: "we (weh)" },
  { symbol: "의", sound: "ui (wee)" },
];

export default data;
