const data = [
  { symbol: "아", sound: "a (aa)" },
  { symbol: "어", sound: "eo (aww)" },
  { symbol: "오", sound: "o (oh)" },
  { symbol: "우", sound: "u (oo)" },
  { symbol: "으", sound: "eu (uh)" },
  { symbol: "이", sound: "i (ee)" },
  { symbol: "애", sound: "ae (eh)" },
  { symbol: "에", sound: "e (eh)" },
  { symbol: "외", sound: "oe (weh)" },
  { symbol: "위", sound: "wi (wee)" },
  { symbol: "ᄀ", sound: "g,k" },
  { symbol: "ᄂ", sound: "n" },
  { symbol: "ᄃ", sound: "d/t" },
  { symbol: "ᄅ", sound: "r,l" },
  { symbol: "ᄆ", sound: "m" },
  { symbol: "ᄇ", sound: "b/p" },
  { symbol: "ᄉ", sound: "s,sh" },
  { symbol: "ᄌ", sound: "j,ch" },
  { symbol: "ᄎ", sound: "ch" },
  { symbol: "ᄏ", sound: "k" },
  { symbol: "ᄐ", sound: "t" },
  { symbol: "ᄑ", sound: "p" },
  { symbol: "ᄒ", sound: "h" },
];

export default data;
